name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GIT_USERNAME: "Sushrut1101"
  GIT_EMAIL: "guptasushrut@gmail.com"
  Branch: "master"
